---
title: "Flex Dashboard with CrossTalk"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(crosstalk)
library(tidyverse)
library(flexdashboard)
library(plotly)
library(leaflet)
download.file("https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/4ef82789-e038-44ef-a478-a8f3590c3eb1/resource/979fb513-5186-41e9-bb23-7b5cc6b89915/download/Apartment%20Building%20Evaluation.csv", "data.csv")
df <- read_csv("data.csv") %>%
        select(lng = LONGITUDE, lat = LATITUDE, SCORE, YEAR_BUILT, SITE_ADDRESS, PROPERTY_TYPE) %>% slice_sample(n = 200)

shared_df <- SharedData$new(df)
```

## Column {data-width="500"}

### **Apartment Audits**

```{r}
icons <- makeIcon(iconUrl = "https://cdn-icons-png.flaticon.com/512/25/25694.png", 
                  iconWidth = 20,
                  iconHeight = 20)

p <- shared_df %>%
        leaflet() %>%
        addTiles() %>%
        addMarkers(~lng, ~lat, popup = ~as.character(paste(sep = "<br/>",SITE_ADDRESS,paste('Score: ',SCORE),paste('Year Built: ',YEAR_BUILT))), label = ~as.character(SITE_ADDRESS), icon = icons)
p
```

## Column {data-width="500"}

### **Data Filters**

```{r}
filter_slider("Score", "SCORE", shared_df, ~SCORE, round = TRUE)
#filter_slider("Year Built", "YEAR_BUILT", shared_df, ~YEAR_BUILT, round = TRUE)
filter_checkbox("Property Type", "PROPERTY_TYPE", shared_df, ~PROPERTY_TYPE, inline = TRUE)

```

### **Year of Development vs Audit Score**

```{r}
p <- shared_df %>%
        ggplot(aes(x = YEAR_BUILT, y = SCORE)) +
        geom_point() +
        geom_smooth(method = "lm")
ggplotly(p)
```
