[build]
publish = "public"
command = "git submodule update --remote --merge && npm run build"

[context.production.environment]
HUGO_VERSION = "0.89.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm run build"

[context.split1.environment]
HUGO_VERSION = "0.89.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run build"

[context.deploy-preview.environment]
HUGO_VERSION = "0.89.0"

[context.branch-deploy]
command = "npm run build"

[context.branch-deploy.environment]
HUGO_VERSION = "0.89.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[plugins]]
package = "netlify-plugin-rss"
  [plugins.inputs]
  # required configs, customize as needed
  dirToScan = "/posts" # a subfolder to scan. "/" to scan all
  authorName = "swyx"
  site_url = "https://swyx.io"
  title = "swyx RSS Feed"
  rssDescription = "swyx.io RSS Feed"
  categories = ['Technology', 'JAMstack', 'Web Development']

  # # optional configs, defaults shown
  # rssFaviconUrl = "https://swyx.io/favicon.png"
  # docs = "http://example.com/rss/docs.html"
  # managingEditor = "authorName"
  # webMaster = "authorName"
  # copyright = "2020 ${authorName}"
  # language = "en"
  # pubDate = "new Date().toUTCString(),"
  # ttl = "60" # aka refresh every hour

  # # cheerio selectors for extractMetadataFromFile
  # # defaults shown
  # contentSelector = "main"
  # publishDateSelector = # if not specified, we use the date of file creation
  # descriptionSelector = "meta[name=description]" # probably no need to change
  # titleSelector = "title" # probably no need to change

  # # developer configs
  # debugMode = false # (for development) turn true for extra diagnostic logging